# .readthedocs.yaml

version: 2  # Required version of the configuration file format

build:
  os: ubuntu-22.04  # OS for building documentation
  tools:
    python: "3.11"  # Python version for the build environment

sphinx:
  configuration: docs/source/conf.py  # Path to Sphinx configuration file

python:
  install:
    - method: pip
      path: .  # Install the project in the Read the Docs environment
    - requirements: requirements.txt  # Path to project's main requirements file

formats:
  - pdf  # Generate a PDF version of the documentation
  - htmlzip  # Generate a zipped HTML version of the documentation
  - epub  # Generate an EPUB version of the documentation

features:
  - skip_random_builds: true  # Skip builds when there are no meaningful changes

build:
  max_time: 3600  # Increase build time limit for large documentation

environment:
  variables:
    READTHEDOCS: "True"  

