# .readthedocs.yaml
version: 2

# Build documentation in the "docs/" directory
sphinx:
  configuration: docs/source/conf.py

# Specify the Python version and additional packages
python:
  version: 3.9  # Use the Python version compatible with your project
  install:
    - requirements: docs/requirements.txt  # Path to your docs-specific requirements file
    - method: pip
      path: .  # Install your project in editable mode

# Build system settings
build:
  image: latest  # Use the latest build image

# Include optional features
features:
  - content_automation: true  # Enables the use of Read the Docs content automation features

# Define environment variables (if any are required for your build)
environment:
  # Example: API keys or configurations
  # MY_API_KEY: "example-key"

