name: dual_autodiff_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11  # Specify Python version
  - pip
  - numpy        # For numerical operations
  - pytest       # For testing
  - cython       # For building C extensions
  - setuptools   # For packaging
  - wheel        # For building wheels
  - sphinx       # For documentation generation
  - matplotlib   # For plotting (if needed)
  - pip:
      - -r requirements.txt  

